query FinancialTransactionDetails($input: FinancialTransactionDetailsQueryArgumentsType!) {
  financialTransactionDetails(input: $input) @stream {
    financialTransactionDetails {
      accountCode
      folioNo
      bucketCode
      invoiceNumber
      invoiceType
      creditYN
      debitYN
      internalYN
      locationID
      paymentType
      roomid
    }
    eventPostingDetails {
      blockBeginDate
      blockEndDate
      allotmentid
      bookId
      checkNumber
      eventpostingid
      eventId
      evPostId
      extraallotmentid
      extraforresvid
      extratranscodeid
      includedallotmentid
      includedforresvid
      businessDate
      insertUser
      organizationID
      revenueType
    }
    accountDetails {
      accountid
      internalAccounttypeid
      accountCode
      accountCreditLimitYn
      accountName
      accountNumber
      accountSname
      accountStatus
      accountType
      accountTypeId
      acctflagreasonid
      accountTypeFlag
      address1
      address2
      address3
      addressId
      age
      agentemployeeid
      agent
      batchStmtYn
      beginDate
      city
      company
      contact
      country
      countryName
      creditLimit
      creditLimitUpdatedOn
      centralBalance
      centralCreditLimit
      centralXchangeDate
      centralXchangeRate
      debtorName
      deletedflag
      dSI
      email
      emailAddr
      emailId
      emailOptInYn
      fax
      faxId
      faxNumber
      flaggedReasonCode
      activeYN
      inactiveDate
      insertDate
      insertUser
      lastRemFaxNo
      locationID
      lstRemPrtDate
      lstRemSent
      lstRemText
      lstStmtNoSent
      nameId
      nAAddress1
      nAAddress2
      nAAddress3
      naCity
      countryCode
      naCountryName
      centralState
      naState
      naStateDescription
      postalCode
      numberOfPersons
      organizationID
      paymentDueDays
      permAccountYN
      phone
      phoneId
      phoneNumber
      primaryKeyID
      primaryYn
      profileid
      supplement
      centralAccountType
      centralFlaggedReasonCode
      repStateDescription
      property
      revenuePool
      state
      stateDescription
      status
      summaryforeigncurrid
      currencyCode
      superSearchIndexText
      updateDate
      updateUser
      upperCaseName
      zip
      balance
      agentUserId
      accountStatusMsg
      lstStmtSent
      lastStmtFaxNo
      monthEndCalcYn
      lastActivityDate
      endDate
    }
    folioTaxDetails {
      billGenerationDate
      folioTime
      billNumber
      folioNo
      folioStyle
      folioTaxSeqNumber
      folioType
      folioType1
    }
    invoicePaymentDetails {
      businessDate
      cashierId
      chainCode
      consumptionTransactionNumber
      consumptionTrx
      cExchangeDate
      cExchangeRate
      deletedFlag
      dSI
      insertDate
      insertUser
      invoicepaymentid
      locationID
      organizationID
      paymentTransactionNumber
      paymentTrx
      primaryKeyID
      property
      rnaInsertDate
      rnaUpdateDate
      updateDate
      updateUser
      appliedAmount
      centralAppliedAmount
      paymentApplicationId
    }
    profileAllInformationDetails {
      guestProfileID
      aRNumber
    }
    rateCodeDetails {
      tieredYN
      transactionCode
      transactionCodeWeekend
      packageTransactionTaxIncludedYN
      transactionTaxWeekendIncludedYN
      updateDate
      updateUser
      upsellYn
      voucherBenefitRateYn
      weekendDays
      wkDeptCode
      yieldableYN
      yieldAs
      ymCode
      addition
      advBaseRateCode
      advBaseRounding
      advanceDailyRateYN
      alternateRateCode
      aSBRateCycle
      availabilityUpdateYn
      backToBackYN
      baseAmount
      baseFltPct
      baseRateCode
      baseRounding
      baseType
      bbarBaseAmount
      bbarBaseRounding
      bbarCompareYn
      bbarYn
      businessDate
      breakfastInclYn
      breakfastPrice
      bypassRankCheckYn
      cateringPackageYN
      commissionablePerc
      commissionableYn
      commissionCode
      commissionPercent
      commissionYn
      complimentaryYN
      currencyCode
      cBaseAmount
      cBbarBaseAmount
      cBreakfastPrice
      cDbaseAmount
      cDoubleRoomSupplementPrice
      cDiscountRateAmount
      cRateFloor
      cRateLevel
      cRodBaseAmount
      cRoomAssignmentValue
      cExchangeDate
      cExchangeRate
      dailyRatesYn
      dayUseYN
      dbaseAmount
      dbaseFltPct
      dbaseRateCode
      dbaseRounding
      dblRoomSupplementPrice
      doubleRoomSupplementYN
      deletedFlag
      depositMaturityPreference
      deptCode
      blockName
      discountRateAmount
      discountRatePercentageYn
      discountYN
      regionalAvailabilityYN
      displaySet
      distributeYn
      dSI
      endDate
      exchangeType
      externallyControlledYN
      extraPersonChargeBegins
      fitDiscountLevel
      fitDiscountPerc
      flatYN
      frequentFlyerYN
      gDSAllowedYN
      groupCode
      highlightRateAmountYn
      houseUseYN
      inactiveDate
      insertDate
      insertUser
      rateLabel
      locationID
      internalLocationId
      longInfo
      loyaltyProgramYN
      mandateResvProfiles
      marketCode
      marketDescription
      marketGroupCode
      marketGroupDescription
      marshaRateProgram
      maximumDaysAdvanceBooking
      maximumLengthOfStay
      maximumOccupancy
      minimumDaysAdvanceBooking
      minimumOccupancy
      mobileCheckinAllowedYn
      mobileChkoutAllowed
      multiplication
      myFidelioUploadYN
      negotiatedYN
      occupancyBasedYn
      occupancyLevel
      operatorType
      orderBy
      organizationID
      internalOrganizationId
      overridePackageYn
      packages
      packageYN
      pendingApprovalYn
      packageTransactionCode
      packageTransactionCodeWeekend
      packageTransactionTaxInclYN
      packageTransactionWkTaxInclYN
      primaryKeyID
      postingRhythmNights
      postingRhythm
      printRateYn
      privilegedRestrictionYn
      privilegedYn
      profitTransactionCode
      propertyName
      rankValue
      rateinfoUrl
      rateUpdateYN
      rateBucket
      rateBucketDescription
      rateCalendarYn
      rateCategory
      rateCategoryDescription
      rateClass
      originalRateCode
      rateCodeId
      rateCodeLockedYn
      rateFloorOverrideYn
      rateIncludesTaxYn
      rateLevel
      redemptionRateYN
      repeatPostingRhythmYn
      centralMarketCode
      centralMarketDescription
      centralMarketGroupCode
      centralMarketGroupDescription
      centralRateBucket
      centralRateBucketDescription
      centralRateCategory
      centralRateCategoryDescription
      centralRateClass
      centralRateClassDescription
      centralRoomType
      centralRoomTypeDescription
      centralSourceCode
      centralSourceDescription
      centralSourceGroupCode
      centralSourceGroupDescription
      property
      rnaInsertDate
      rnaUpdateDate
      rodBaseAmount
      rodBaseFltPct
      rodBaseRounding
      rodYn
      roomAssignmentValue
      roomType
      roomTypeDescription
      sdowEndBookingDate
      displaySequence
      serviceInclYn
      servicePerc
      shortInfo
      showRateAmountYn
      sourceCode
      sourceDescription
      sourceGroupCode
      sourceGroupDescription
      taxIncludedPerc
      taxIncludedYn
      eventProperty
      advanceDailyBaseYN
      rankAdjustmentFactor
      unitOfLengthOfStay
      orsSellSequence
      changeState
      rateFloor
      currCodeDecimalPos
      rodBasedYn
      catPackageCode
      daysWhenClosedToArrival
      folioText
      defaultToHighestBarYn
      mfnUploadYn
      sdowBeginBookingDate
      bbarBasedYn
      bbarBaseFltPct
      dbaseCompareYn
      advanceBaseCompareYN
      bypassHurdleYn
      ownerRateYN
      rateClassDescription
    }
    reservationDetails {
      reservationType
      reservationTypeDescription
      guestprofileid
      gueststatusid
      guesttypeid
      resvGuid
      resvNameid
      reservationNameID
      resvNumber
      reservationStatus
      room
      roomcategoryid
      roomid
    }
    roomDetails {
      areaF
      areaM
      assignemployeeid
      assignreasonid
      assignAssignStatus
      assignDate
      roomCondition
      assignReasonDesc
      assignType
      bedType
      building
      buildingGroup
      businessDate
      combinationRoomYN
      comments
      componentRoom
      connectingRoomNumber
      stayoverCredits
      departureCredits
      pickupCredits
      turndownCredits
      cMinimumRevenue
      cRackRate
      cExchangeDate
      cExchangeRate
      defatulratecodeid
      publishedRateCode
      defaultRateDesc
      deletedflag
      description
      diarydisplayflag
      diaryName
      discrepancy
      doors
      dSI
      evisitorFacilityId
      facing
      floor
      forceAlternateYn
      foPers
      frontOfficeStatus
      frontDeskLocation
      fullUtilizationTime
      handicapflag
      heightmaxF
      heightmaxM
      heightminM
      accessible
      housekeepingAssignmentOrderBy
      eveningSection
      housekeepingInspDate
      housekeepingInspEmpId
      housekeepingPers
      daySection
      housekeepingStatus
      holdDateTime
      holdType
      imageId
      inactiveflag
      insertDate
      insertUser
      keyCode
      keyOptions
      lastCheckOutDate
      lengthF
      lengthM
      light
      locationID
      loudspeakersflag
      maxCapacity
      maximumOccupancy
      maxSharedGroups
      meetingRoomYN
      meetingRoomType
      meetingroomTypeDesc
      meetingroomTypeSeq
      microphoneSocketTypes
      minimumRevenue
      minAdvance
      minCapacity
      numberOfBeds
      occupancyCondition
      occupantDiscrepancy
      onlinePrintingYn
      sequence
      orderBy2
      orderBy3
      orderBy4
      orderBy5
      organizationID
      ovosUnitYn
      roomParity
      pcode
      personDiscrepancy
      phoneNumber
      physicalNumberOfRooms
      primaryKeyID
      pseudoRoomYN
      publishedRateAmount
      rateCode
      supplement
      repAssignReasonDescription
      repBedTypeDescription
      centralMeetingRoomType
      repMeetingroomTypeDescription
      repMeetingroomTypeSequence
      centralRoomType
      centralRoomTypeDescription
      centralRoomClass
      roomClassCentralDescription
      repRoomClassSellSequence
      repRoomFeaturesDescs
      repRoomStatusReason
      repRoomStatusReasonDescription
      property
      returnStatus
      roomStatusFromDate
      roomStatusRemarks
      roomStatusToDate
      roomNumber
      roomcategoryid
      roomclassid
      roomid
      room
      roomstatusreasonid
      rating
      roomAssignmentRating
      roomType
      roomCategoryBedtype
      roomCategoryDesc
      genericYN
      suiteYN
      roomClass
      roomClassDescription
      roomClassSequence
      roomFeatureDescription
      roomStatus
      roomStatusDescription
      roomStatusReason
      roomStatusReasonDesc
      roomUseCount
      serviceStatus
      setupNotes
      shareableflag
      smoking
      smokingPreferences
      squareUnits
      suiteType
      internalTempflag
      tempFlag
      translationboothNum
      turnDown
      tvRadioSockets
      unit
      updateDate
      updateUser
      visibleOnWebYn
      webBookingYn
      weightF
      weightM
      widthF
      widthM
      holdUser
      maxAdvance
      heightminF
      roomFeatures
      microphoneSockets
      ovosGradeCode
      excludedEventTypes
      lastMeterReading
      measurement
    }
    transactionCodeDetails {
      accountingCode
      accountNumber
      acctrecvprofileid
      adjtranscodeid
      arrangementCode
      arrangeCode
      aRNameId
      cCCode
      ccType
      checkNumberMandatoryYN
      class1MandatoryYn
      commissionCode
      compNightsYn
      compPaymentYn
      complimentaryYN
      corporateDescription
      corpPropFlag
      cRSTaxDesc
      currencyCode
      cDefaultPrice
      cExportBucket
      cMaxAmount
      cMinimumAmount
      cExchangeDate
      cExchangeRate
      dailyPlanFolio
      dedOwnerRevenueYN
      defaultPrice
      chargeDeferredUntilCheckoutYN
      deletedFlag
      depositPostingOnlyYn
      depositType
      transactionCodeDescription
      dSI
      expenseFolio
      exportBucket
      externalPaymentCode
      fiscalPaymentYn
      fiscalTrxCodeType
      foreignCurrencyID
      membershipYN
      groupPointsRedemptionYN
      groupFolio
      groupClass1MandatoryYN
      gDeletedFlag
      gDescription
      groupIndRevenueGroup
      gInsertDate
      gInsertUser
      groupInternalYN
      gOrderBy
      gRepDescription
      groupRepItem
      groupRepItemName
      groupRepOrderBy
      centralTransactionCodeGroup
      groupRepUpdateDate
      gResultIncludedInSumArray
      gRevenuegroupflag
      gTctClassType1
      gTctClassType2
      groupTcTransactionType
      gUpdateDate
      gUpdateUser
      inactiveflag
      inactiveDate
      includeIn8300Yn
      includeInDepositRuleYn
      aRLedgerPaymentsYN
      guestLedgerPaymentsYN
      cashTransactionCodeYN
      depositLedgerPaymentsYN
      revenueYN
      crossPostingPaymentYN
      insertDate
      insertUser
      internalYn
      manualPostingAllowedYN
      locationID
      manualPostCoversYn
      maximumAmount
      minimumAmount
      nonTaxableYn
      organizationID
      ownerRevenueYN
      paymentTaxInvoiceYn
      paymentType
      primaryKeyID
      printReceiptYN
      processingType
      quantityCode
      centralAdjustmentTransactionCode
      repDescription
      repItemName
      repItemOrderby
      centralTransactionCode
      repUpdateDate
      property
      resultIncludedInSumArray
      revenueGroupId
      rnaInsertDate
      rnaUpdateDate
      rotationRevenueYN
      roundFactorYn
      serviceRecoveryTrxCode
      subGroupClass1MandatoryYN
      subGroupClass2MandatoryYN
      sgDescription
      subGroupFrequentFlyerYN
      subGroupGroupPointsRedemptionYN
      subGroupIndRevenueGroup
      sgInsertDate
      sgInsertUser
      subGroupInternalYN
      sgOrderBy
      subGroupRepDescription
      subGroupRepOrderBy
      centalSubgroup
      sgResultIncludedInSumArray
      sgRevenuegroupflag
      subGroupType
      sgTaxflag
      taxYN
      subGroupTcGroupAndSubgroup
      subGroupTcTransactionType
      sgUpdateDate
      sgUpdateUser
      taxCodeNumber
      taxInclusiveYN
      tclCodeDfltCl1
      tclCodeDfltCl2
      tcBofInterface
      tcBofInterface2
      tcBofRefCode
      tcBofRefCode2
      group
      transactionCodeResort
      tcResort2
      transactionCodeSubGroup
      tcTransactionType
      transactionType
      transcodeid
      transactionCodeGroup
      internalTransactionCodeSubGroup
      transactionActionId
      trxCode
      trxCodeDisplay
      transactionCodeType
      trxServiceType
      trxTaxTypeCode
      uPC
      updateUser
      crossPostingDepositYN
      crossPostingSalesYN
      adjTrxCode
      class2MandatoryYn
      eInvoiceYn
      groupClass2MandatoryYN
      groupRepItemOrderby
      paymentmethodid
      repItem
      revenueBucketId
      sgDeletedFlag
      internalDeletedflag
      transcodearrangementid
      updateDate
    }
  }
}