query ProfilesIndividuals($input: ProfilesIndividualsQueryArgumentsType!, $limit: Int) {
    profilesIndividuals(input: $input, limit: $limit) @stream {
        profileAllInformationDetails {
            profileId
            firstName
            guestMiddleName
            guestLastName
        }
    }
}