query BookingsReservation($input: BookingsReservationQueryArgumentsType!, $limit: Int){
  bookingsReservation(input: $input, limit: $limit) @stream {
    reservationDetails {
      resvNameid
    }
  }
}